---
title: "6. Web Scraping"
order: 6
---

## Tutorials

1. [Introduction to Web Scraping](scraping-1.qmd)
2. [More Scraping + actionability](scraping-2.qmd)
3. [Writing executable scripts with Argparse](scraping-3.qmd)
4. [Playwright + Argparse + Streamlit to create useful apps](scraping-4.qmd)

## Lectures

### Monday 11/3/25

Introduction to web scraping

<iframe id="kmsembed-1_6uihcnf6" width="640" height="360" src="https://video.syr.edu/embed/secure/iframe/entryId/1_6uihcnf6/uiConfId/45992161/st/0" class="kmsembed" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" referrerPolicy="no-referrer-when-downgrade" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="IST 356 Lecture - 11-3-25"></iframe>

### Wednesday 11/5/25

More scraping + actionability

<iframe id="kmsembed-1_h83r4i0l" width="640" height="360" src="https://video.syr.edu/embed/secure/iframe/entryId/1_h83r4i0l/uiConfId/45992161/st/0" class="kmsembed" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" referrerPolicy="no-referrer-when-downgrade" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="IST 356 Lecture - 11-5-25"></iframe>


### Monday 11/10/25

Writing executable scripts with Argparse

<iframe id="kmsembed-1_sj8lyhfz" width="640" height="360" src="https://video.syr.edu/embed/secure/iframe/entryId/1_sj8lyhfz/uiConfId/45992161/st/0" class="kmsembed" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" referrerPolicy="no-referrer-when-downgrade" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="IST 356 Lecture - 11-10-25"></iframe>

### Wednesday 11/12/25

Playwright + Argparse + Streamlit to create useful apps

<iframe id="kmsembed-1_r9o46390" width="640" height="360" src="https://video.syr.edu/embed/secure/iframe/entryId/1_r9o46390/uiConfId/45992161/st/0" class="kmsembed" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" referrerPolicy="no-referrer-when-downgrade" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="IST 356 Lecture - 11-12-25"></iframe>
