---
title: "2. Python review"
order: 2
---

In this unit we will review some basics of Python programming. You will have covered the material here in IST 256.

## Tutorials

1. [Input, output, variables, types, conditionals](python-1.qmd)
2. [Iterations, lists, dictionaries, comprehensions](python-2.qmd)
3. [Functions, documentation, strings, files](python-3.qmd)
4. [Modules, import, pip, testing](python-4.qmd)

## Lectures

## Wednesday, 9/3/2025

Instructions on how to use GitHub Classroom; start of Python review.

<iframe id="kmsembed-1_vpojfecb" width="640" height="360" src="https://video.syr.edu/embed/secure/iframe/entryId/1_vpojfecb/uiConfId/45992161/st/0" class="kmsembed" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" referrerPolicy="no-referrer-when-downgrade" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="IST 356 Lecture - 9-3-25"></iframe>

## Monday, 9/8/2025

Continuation of Python review: conditionals, loops, lists, and dictionaries (2 parts)

<iframe id="kmsembed-1_vpojfecb" width="640" height="360" src="https://video.syr.edu/embed/secure/iframe/entryId/1_vfmptnc4/uiConfId/45992161/st/0" class="kmsembed" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" referrerPolicy="no-referrer-when-downgrade" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="IST 356 Lecture - 9-3-25"></iframe>

<iframe id="kmsembed-1_vpojfecb" width="640" height="360" src="https://video.syr.edu/embed/secure/iframe/entryId/1_oa086gbk/uiConfId/45992161/st/0" class="kmsembed" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" referrerPolicy="no-referrer-when-downgrade" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="IST 356 Lecture - 9-3-25"></iframe>

## Wednesday, 9/10/2025

Continuation of Python review: functions, strings, and files

<iframe id="kmsembed-1_vpojfecb" width="640" height="360" src="https://video.syr.edu/embed/secure/iframe/entryId/1_dm1z4h65/uiConfId/45992161/st/0" class="kmsembed" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" referrerPolicy="no-referrer-when-downgrade" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="IST 356 Lecture - 9-3-25"></iframe>

## Monday, 9/15/2025

Finishing Python review: modules and testing

<iframe id="kmsembed-1_bx69379t" width="640" height="360" src="https://video.syr.edu/embed/secure/iframe/entryId/1_bx69379t/uiConfId/45992161/st/0" class="kmsembed" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" referrerPolicy="no-referrer-when-downgrade" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="IST 356 Lecture - 9-15-25"></iframe>
