---
title: "7. Visualization"
order: 7
---

## Tutorials

1. [Introduction to maptlotlib and seaborn](visualization-1.qmd) 
2. [More Seaborn plots](visualization-2.qmd)

## Lectures

### Monday 11/17/25

Introduction to matplotlib and seaborn

<iframe id="kmsembed-1_nxfmrd91" width="640" height="360" src="https://video.syr.edu/embed/secure/iframe/entryId/1_nxfmrd91/uiConfId/45992161/st/0" class="kmsembed" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" referrerPolicy="no-referrer-when-downgrade" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="IST 356 Lecture - 11-17-25"></iframe>


### Wednesday 11/19/25

Final project overview; more Seaborn plots

*Note*: Around the 35:00 mark, I switched back from the iPad to the computer. Unfortunately the focus did not switch from my iPad to my laptop in the Zoom recording, so you can only see VS code in the small inset. I was basically follwoing the [tutorial](visualization-2.qmd); refer to that for to see the commands I was using.

<iframe id="kmsembed-1_3tumyoga" width="640" height="360" src="https://video.syr.edu/embed/secure/iframe/entryId/1_3tumyoga/uiConfId/45992161/st/0" class="kmsembed" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" referrerPolicy="no-referrer-when-downgrade" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="IST 356 Lecture - 11-19-25"></iframe>
