---
title: "4. Data Wrangling"
order: 4
---

In this unit we will learn about how to easily manage and manipulate data in Python using NumPy and Pandas.

## Tutorials

1. [Introduction to NumPy](numpy_basics.qmd)
2. [Introduction to Pandas: Series and DataFrames](pandas-1.qmd)
3. [Data I/O with Pandas](pandas-2.qmd)
4. [Joining Multiple Pandas Dataframes](pandas-3.qmd)
5. [Basic data cleaning with Pandas](pandas-4.qmd)
6. [Grouping data and creating pivot tables with Pandas](pandas-5.qmd)

## Lectures


### Monday, 9/22/2025

Instructions on how to use Git on the command line. Introduction to NumPy.

<iframe id="kmsembed-1_nkv9vmc2" width="640" height="360" src="https://video.syr.edu/embed/secure/iframe/entryId/1_nkv9vmc2/uiConfId/45992161/st/0" class="kmsembed" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" referrerPolicy="no-referrer-when-downgrade" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="IST 356 Lecture - 9-22-25"></iframe>

### Wednesday, 9/24/2025

Introduction to Pandas: Series and DataFrames.

<iframe id="kmsembed-1_x1e3dgg7" width="640" height="360" src="https://video.syr.edu/embed/secure/iframe/entryId/1_x1e3dgg7/uiConfId/45992161/st/0" class="kmsembed" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" referrerPolicy="no-referrer-when-downgrade" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="IST 356 Lecture - 9-24-25"></iframe>

### Monday, 9/29/2025

Data I/O with Pandas

<iframe id="kmsembed-1_secnsb0c" width="640" height="360" src="https://video.syr.edu/embed/secure/iframe/entryId/1_secnsb0c/uiConfId/45992161/st/0" class="kmsembed" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" referrerPolicy="no-referrer-when-downgrade" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="IST 356 Lecture - 9-29-25"></iframe>

### Wednesday, 10/1/2025

Joining mulitple DataFrames

<iframe id="kmsembed-1_afvt5pi9" width="640" height="360" src="https://video.syr.edu/embed/secure/iframe/entryId/1_afvt5pi9/uiConfId/45992161/st/0" class="kmsembed" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" referrerPolicy="no-referrer-when-downgrade" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="IST 356 Lecture - 10-1-25"></iframe>

### Monday, 10/6/2025

Using `apply` to clean data in a Pandas DataFrame

<iframe id="kmsembed-1_yopjqnmf" width="640" height="360" src="https://video.syr.edu/embed/secure/iframe/entryId/1_yopjqnmf/uiConfId/45992161/st/0" class="kmsembed" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" referrerPolicy="no-referrer-when-downgrade" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="IST 356 Lecture - 10-6-25"></iframe>

### Wednesday, 10/8/2025

Grouping data, merging tables, and creating pivot tables

<iframe id="kmsembed-1_uipdgyio" width="640" height="360" src="https://video.syr.edu/embed/secure/iframe/entryId/1_uipdgyio/uiConfId/45992161/st/0" class="kmsembed" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" referrerPolicy="no-referrer-when-downgrade" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="IST 356 Lecture - 10-8-25"></iframe>
