---
title: "3. UI"
order: 3
---

In this unit we will learn about some useful Python modules for creating dynamic user interface (UI) to your code.

## Tutorials

1. [Interaction in Jupyter using ipywidgets](ui-1.qmd)
2. [Creating simple web apps with Streamlit](ui-2.qmd)

## Lectures

## Wednesday, 9/17/2025

Walkthrough of how to run pytest in VS Code; Jupyter Widgets and Streamlit

<iframe id="kmsembed-1_ikmnfhvf" width="640" height="360" src="https://video.syr.edu/embed/secure/iframe/entryId/1_ikmnfhvf/uiConfId/45992161/st/0" class="kmsembed" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" referrerPolicy="no-referrer-when-downgrade" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="IST 356 Lecture - 9-17-25"></iframe>
