---
title: "1. Command line interface and Environments"
order: 1
---

In this unit, you will learn how to use the bash shell in a command line interface (CLI), programming environments, and how to use `conda` to manage environments and install packages.

# Lecture

## Wednesday, 8/28/2025

<div style="max-width:640px"><div style="position:relative;padding-bottom:56.25%"><iframe id="kmsembed-1_ncidn6a1" width="640" height="360" src="https://video.syr.edu/embed/secure/iframe/entryId/1_ncidn6a1/uiConfId/45992161/st/0" class="kmsembed" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" referrerPolicy="no-referrer-when-downgrade" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="IST 356 Lecture - 8-27-25" style="position:absolute;top:0;left:0;width:100%;height:100%;border:0"></iframe></div></div>

## Tutorials

1. [Introduction to CLI](shell-intro.qmd)

1. [Environments and Conda](conda.qmd)
